// Generated by CoffeeScript 1.7.1
(function() {
  var deepFreeze;

  module.exports = deepFreeze = function(o) {
    var prop, _i, _len, _ref;
    Object.freeze(o);
    _ref = Object.getOwnPropertyNames(o);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      prop = _ref[_i];
      if (o.hasOwnProperty(prop) && (o[prop] != null) && (typeof o[prop] === 'object' || typeof o[prop] === 'function') && !Object.isFrozen(o[prop])) {
        deepFreeze(o[prop]);
      }
    }
    return o;
  };

}).call(this);
