// Generated by CoffeeScript 1.7.1
(function() {
  var isPlainObject;

  isPlainObject = function(o) {
    return (o != null) && toString.call(o) === '[object Object]';
  };

  module.exports = function(src, data) {
    var dst, key;
    dst = Array.isArray(src) ? [] : {};
    for (key in src) {
      dst[key] = src[key];
    }
    for (key in data) {
      if (isPlainObject(data[key]) && isPlainObject(src[key])) {
        dst[key] = deepMerge(src[key], data[key]);
      } else {
        dst[key] = data[key];
      }
    }
    return Object.freeze(dst);
  };

}).call(this);
