// Generated by CoffeeScript 1.7.1
(function() {
  var deepMerge, isPlainObject;

  isPlainObject = require('./is_plain_object');

  module.exports = deepMerge = function(src, data) {
    var dst, key;
    dst = Array.isArray(src) ? [] : {};
    for (key in src) {
      dst[key] = src[key];
    }
    for (key in data) {
      if (isPlainObject(data[key]) && isPlainObject(src[key])) {
        dst[key] = deepMerge(src[key], data[key]);
      } else {
        dst[key] = data[key];
      }
    }
    return dst;
  };

}).call(this);
