// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(o) {
    var k, v;
    for (k in o) {
      v = o[k];
      if (o.hasOwnProperty(k)) {
        return false;
      }
    }
    return true;
  };

}).call(this);
